spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smxsonar_09_05_19?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    password: root
    username: root
  batch:
    initialize-schema: always
    job:
      enabled: false
logging:
  level:
    ROOT: info